/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIConnection */

#ifndef _Included_JNIConnection
#define _Included_JNIConnection
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIConnection
 * Method:    main
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNIConnection_main
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
